import { CONFIG } from './config.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const angleDiff=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
const rand=(a,b)=>a+Math.random()*(b-a);

export class Game {
  constructor(canvas, input, ui) {
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.input=input;this.ui=ui;
    this.state='menu';this.wave=0;this.player=null;this.enemies=[];this.shots=[];this.particles=[];this.tracks=[];this.camera={x:0,y:0,shake:0};
    this.last=0;this.accumulator=0;this.kills=0;this.ultKills=0;this.ults=0;this.elapsed=0;this.spawnQueue=0;this.spawnClock=0;this.upgrades=[];this.stats={damageTaken:0};
    this.obstacles=[];this.makeMap();
  }
  makeMap(){
    this.obstacles=[];
    // A few cover clusters leave broad lanes around the center.
    for(let i=0;i<24;i++){
      const x=rand(170,CONFIG.world.width-170),y=rand(170,CONFIG.world.height-170);
      if(Math.hypot(x-1100,y-1100)<260)continue;
      const type=Math.random()<.55?'rock':'crate';this.obstacles.push({x,y,r:type==='rock'?rand(24,44):30,type,hp:type==='rock'?999:65,maxHp:type==='rock'?999:65});
    }
  }
  start(){this.state='playing';this.wave=0;this.kills=0;this.ultKills=0;this.ults=0;this.elapsed=0;CONFIG.ultimate.killsRequired=10;this.stats={damageTaken:0};this.enemies=[];this.shots=[];this.particles=[];this.tracks=[];this.obstacles=this.obstacles.map(o=>({...o,hp:o.maxHp}));this.player={x:1100,y:1100,vx:0,vy:0,angle:-Math.PI/2,turret:-Math.PI/2,hp:100,maxHp:100,armor:5,speed:205,damage:34,fireRate:.48,projectileSpeed:590,reload:0,invuln:0};this.camera.x=this.player.x;this.camera.y=this.player.y;this.ui.hideAll();this.startWave();}
  startWave(){this.wave++;this.state='playing';const w=CONFIG.waves[this.wave-1];this.spawnQueue=w.count+(w.escorts||0);this.spawnClock=.5;this.ui.waveBanner(this.wave);if(w.boss)this.ui.bossToast();}
  update(dt){
    if(this.state!=='playing')return;this.elapsed+=dt;this.playerUpdate(dt);this.spawnUpdate(dt);this.enemyUpdate(dt);this.projectileUpdate(dt);this.particleUpdate(dt);this.trackUpdate(dt);this.cameraUpdate(dt);
    if(this.spawnQueue<=0&&this.enemies.length===0)this.completeWave();
    this.ui.updateHud(this);
  }
  playerUpdate(dt){const p=this.player,I=this.input,{x,y}=I.movement;let throttle=clamp(y,-1,1),turn=clamp(x,-1,1);if(Math.abs(throttle)>.04){p.angle+=turn*CONFIG.player.rotationSpeed*dt*(throttle<0?-.78:1);}else if(Math.abs(turn)>.08&&Math.abs(x)>.5){p.angle+=turn*CONFIG.player.rotationSpeed*.42*dt;}
    const forward=Math.cos(p.angle)*p.vx+Math.sin(p.angle)*p.vy;const target=throttle>=0?throttle*p.speed:throttle*CONFIG.player.reverseSpeed;const accel=(Math.abs(target)<Math.abs(forward)?CONFIG.player.braking:CONFIG.player.acceleration)*dt;const next=forward+clamp(target-forward,-accel,accel);p.vx=Math.cos(p.angle)*next;p.vy=Math.sin(p.angle)*next;p.x=clamp(p.x+p.vx*dt,30,CONFIG.world.width-30);p.y=clamp(p.y+p.vy*dt,30,CONFIG.world.height-30);if(Math.abs(throttle)<.03){p.vx*=Math.exp(-CONFIG.player.friction*dt);p.vy*=Math.exp(-CONFIG.player.friction*dt);}
    // Mouse position is screen-space; convert to world using camera.
    let aimAngle=p.turret;if(Math.hypot(I.aim.x,I.aim.y)>.08)aimAngle=Math.atan2(I.aim.y,I.aim.x);else if(I.mouse.x||I.mouse.y){const wx=I.mouse.x-this.canvas.clientWidth/2+this.camera.x,wy=I.mouse.y-this.canvas.clientHeight/2+this.camera.y;aimAngle=Math.atan2(wy-p.y,wx-p.x);}p.turret+=clamp(angleDiff(p.turret,aimAngle),-CONFIG.player.turretRotationSpeed*dt,CONFIG.player.turretRotationSpeed*dt);
    p.reload=Math.max(0,p.reload-dt);p.invuln=Math.max(0,p.invuln-dt);if(I.firing&&p.reload<=0)this.fire(p,'player');if(I.ultimatePressed&&this.ultKills>=CONFIG.ultimate.killsRequired)this.fireUltimate();
    for(const o of this.obstacles){const dx=p.x-o.x,dy=p.y-o.y,d=Math.hypot(dx,dy),min=p.radius+o.r;if(d<min&&d>0){p.x+=dx/d*(min-d);p.y+=dy/d*(min-d);p.vx*=.75;p.vy*=.75;}}
    if(Math.hypot(p.vx,p.vy)>45&&Math.random()<dt*6)this.tracks.push({x:p.x-Math.cos(p.angle)*15,y:p.y-Math.sin(p.angle)*15,a:p.angle,life:8});
  }
  spawnUpdate(dt){if(this.spawnQueue<=0)return;this.spawnClock-=dt;if(this.spawnClock<=0){this.spawnClock=CONFIG.difficulty.spawnEvery;const w=CONFIG.waves[this.wave-1];this.spawnEnemy(Boolean(w.boss&&this.spawnQueue===1));this.spawnQueue--;}}
  spawnEnemy(boss=false){const p=this.player;let a=rand(0,Math.PI*2),dist=rand(500,760),x=clamp(p.x+Math.cos(a)*dist,60,CONFIG.world.width-60),y=clamp(p.y+Math.sin(a)*dist,60,CONFIG.world.height-60);const cfg=CONFIG.waves[this.wave-1];const isBoss=boss;const hp=CONFIG.enemy.hp*cfg.hp*(isBoss?4.2:1);this.enemies.push({x,y,vx:0,vy:0,angle:a+Math.PI,turret:a+Math.PI,hp,maxHp:hp,radius:isBoss?37:CONFIG.enemy.radius,armor:isBoss?7:CONFIG.enemy.armor,speed:CONFIG.enemy.speed*cfg.speed*(isBoss?.76:1),damage:CONFIG.enemy.damage*cfg.damage*(isBoss?1.55:1),fireRate:CONFIG.enemy.fireRate*(isBoss?.76:1),reload:rand(.6,1.5),boss:isBoss,orbit:Math.random()<.5?-1:1,flash:0});}
  enemyUpdate(dt){for(const e of this.enemies){const p=this.player,dx=p.x-e.x,dy=p.y-e.y,d=Math.max(1,Math.hypot(dx,dy)),desired=Math.atan2(dy,dx),diff=angleDiff(e.angle,desired);e.angle+=clamp(diff,-1.8*dt,1.8*dt);e.turret+=clamp(angleDiff(e.turret,desired),-2.7*dt,2.7*dt);let move= d>300?1:d<210?-.7:.35*e.orbit;e.vx=Math.cos(e.angle)*e.speed*move;e.vy=Math.sin(e.angle)*e.speed*move;e.x=clamp(e.x+e.vx*dt,35,CONFIG.world.width-35);e.y=clamp(e.y+e.vy*dt,35,CONFIG.world.height-35);for(const o of this.obstacles){const ox=e.x-o.x,oy=e.y-o.y,od=Math.hypot(ox,oy),min=e.radius+o.r;if(od<min&&od>0){e.x+=ox/od*(min-od);e.y+=oy/od*(min-od);e.orbit*=-1;}}e.reload-=dt;if(e.reload<=0&&d<680){this.fire(e,'enemy');e.reload=e.fireRate*rand(.8,1.25);}e.flash=Math.max(0,e.flash-dt);}}
  fire(owner,team){const ult=false;this.shot(owner,team,ult);if(team==='player')owner.reload=owner.fireRate;}
  shot(owner,team,ult=false){if(this.shots.length>=CONFIG.graphics.maxProjectiles)return;const a=owner.turret,range=owner.radius+8;this.shots.push({x:owner.x+Math.cos(a)*range,y:owner.y+Math.sin(a)*range,vx:Math.cos(a)*(ult?CONFIG.player.ultimateSpeed:team==='player'?owner.projectileSpeed:CONFIG.enemy.projectileSpeed),vy:Math.sin(a)*(ult?CONFIG.player.ultimateSpeed:team==='player'?owner.projectileSpeed:CONFIG.enemy.projectileSpeed),damage:ult?CONFIG.player.ultimateDamage:team==='player'?owner.damage:owner.damage,team,life:ult?2.4:2.3,r:ult?10:5,penetration:ult?CONFIG.player.ultimatePenetration:0,explosion:ult?CONFIG.player.ultimateRadius:0,ult});this.burst(owner.x+Math.cos(a)*range,owner.y+Math.sin(a)*range,ult?'#ffe78a':'#ffbd5a',ult?16:6);this.camera.shake=Math.max(this.camera.shake,ult?14:2);}
  fireUltimate(){this.shot(this.player,'player',true);this.ultKills-=CONFIG.ultimate.killsRequired;this.ults++;this.ui.toast('СУПЕРВЫСТРЕЛ!');}
  projectileUpdate(dt){for(let i=this.shots.length-1;i>=0;i--){const b=this.shots[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;const targets=b.team==='player'?this.enemies:[this.player];for(const t of targets){if(Math.hypot(t.x-b.x,t.y-b.y)<t.radius+b.r){const damage=Math.max(b.damage-(t.armor||0),b.damage*.1);t.hp-=damage;t.flash=.12;this.burst(b.x,b.y,'#ffdc8a',8);if(t===this.player)this.stats.damageTaken+=damage;if(t.hp<=0){if(t===this.player){this.playerDead();}else{this.kills++;this.ultKills++;this.burst(t.x,t.y,t.boss?'#ff923b':'#e96540',t.boss?34:20);}}if(b.explosion){for(const u of this.enemies){const d=Math.hypot(u.x-b.x,u.y-b.y);if(u!==t&&d<b.explosion+u.radius){u.hp-=b.damage*(1-d/(b.explosion+u.radius));if(u.hp<=0){this.kills++;this.ultKills++;this.burst(u.x,u.y,'#ff923b',20);}}}}if(b.penetration>0)b.penetration--;else hit=true;break;}}
      if(!hit)for(const o of this.obstacles){if(Math.hypot(o.x-b.x,o.y-b.y)<o.r+b.r){if(o.type==='crate'){o.hp-=b.damage;if(o.hp<=0){this.burst(o.x,o.y,'#ba956c',14);this.obstacles.splice(this.obstacles.indexOf(o),1);}}this.burst(b.x,b.y,'#ffd589',5);hit=true;break;}}
      if(hit||b.life<=0||b.x<0||b.y<0||b.x>CONFIG.world.width||b.y>CONFIG.world.height)this.shots.splice(i,1);
    }this.enemies=this.enemies.filter(e=>e.hp>0);}
  burst(x,y,color,n){for(let i=0;i<n&&this.particles.length<CONFIG.graphics.maxParticles;i++){const a=rand(0,Math.PI*2),s=rand(25,220);this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.75),max:.75,r:rand(2,6),color});}}
  particleUpdate(dt){for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-2*dt);p.vy*=Math.exp(-2*dt);p.life-=dt;if(p.life<=0)this.particles.splice(i,1);}}
  trackUpdate(dt){for(const t of this.tracks)t.life-=dt;this.tracks=this.tracks.filter(t=>t.life>0).slice(-180);}
  cameraUpdate(dt){this.camera.x+=(this.player.x-this.camera.x)*Math.min(1,dt*5);this.camera.y+=(this.player.y-this.camera.y)*Math.min(1,dt*5);this.camera.shake=Math.max(0,this.camera.shake-dt*24);}
  completeWave(){this.state='upgrade';if(this.wave>=CONFIG.waves.length){this.state='victory';this.ui.showEnd(true,this);return;}this.ui.showUpgrades(this.getUpgrades());}
  getUpgrades(){const defs=[{name:'Усиленный снаряд',desc:'+25% урона',rarity:'ОБЫЧНОЕ',apply:()=>this.player.damage*=1.25},{name:'Быстрая перезарядка',desc:'+20% скорострельности',rarity:'ОБЫЧНОЕ',apply:()=>this.player.fireRate*=.8},{name:'Дополнительная броня',desc:'+25 к максимуму HP и ремонт',rarity:'РЕДКОЕ',apply:()=>{this.player.maxHp+=25;this.player.hp=Math.min(this.player.maxHp,this.player.hp+25);}},{name:'Турбина',desc:'+20% скорости движения',rarity:'ОБЫЧНОЕ',apply:()=>this.player.speed*=1.2},{name:'Большой калибр',desc:'+35% урона, но -10% скорострельности',rarity:'ЭПИЧЕСКОЕ',apply:()=>{this.player.damage*=1.35;this.player.fireRate*=1.1;}},{name:'Полевой ремонт',desc:'Восстановить 45 HP',rarity:'РЕДКОЕ',apply:()=>this.player.hp=Math.min(this.player.maxHp,this.player.hp+45)},{name:'Энергосбор',desc:'Супервыстрел заряжается за 8 убийств',rarity:'ЭПИЧЕСКОЕ',apply:()=>CONFIG.ultimate.killsRequired=8}];return [...defs].sort(()=>Math.random()-.5).slice(0,3);}
  chooseUpgrade(index){const u=this.upgrades[index];if(!u)return;u.apply();this.upgrades=[];this.ui.hideAll();this.startWave();}
  togglePause(){if(this.state==='playing'){this.state='paused';this.ui.showPause();}else if(this.state==='paused'){this.state='playing';this.ui.hideAll();}}
  playerDead(){if(this.state!=='playing')return;this.burst(this.player.x,this.player.y,'#f17442',34);this.state='gameover';this.ui.showEnd(false,this);}
  render(){const c=this.ctx,w=this.canvas.clientWidth,h=this.canvas.clientHeight;c.clearRect(0,0,w,h);c.save();let sx=(Math.random()-.5)*this.camera.shake,sy=(Math.random()-.5)*this.camera.shake;c.translate(w/2-this.camera.x+sx,h/2-this.camera.y+sy);this.drawWorld(c);this.drawTracks(c);for(const o of this.obstacles)this.drawObstacle(c,o);for(const b of this.shots)this.drawShot(c,b);for(const e of this.enemies)this.drawTank(c,e,false);if(this.player)this.drawTank(c,this.player,true);for(const p of this.particles){c.globalAlpha=Math.max(0,p.life/p.max);c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.r*(.5+p.life/p.max),0,Math.PI*2);c.fill();}c.globalAlpha=1;c.restore();}
  drawWorld(c){const W=CONFIG.world.width,H=CONFIG.world.height;c.fillStyle='#344638';c.fillRect(0,0,W,H);c.fillStyle='#3c4d3e';for(let y=0;y<H;y+=CONFIG.world.grid)for(let x=0;x<W;x+=CONFIG.world.grid){if(((x/100+y/100)%3)===0){c.globalAlpha=.18;c.fillRect(x+12+(x*13+y*7)%35,y+9+(x*3+y*11)%32,18+(x+y)%19,6+(x*5+y)%9);}}c.globalAlpha=1;c.strokeStyle='rgba(213,197,139,.14)';c.lineWidth=46;c.setLineDash([65,40]);c.beginPath();c.moveTo(100,1100);c.lineTo(2100,1100);c.stroke();c.setLineDash([]);c.strokeStyle='#82906b';c.lineWidth=8;c.strokeRect(8,8,W-16,H-16);}
  drawTracks(c){for(const t of this.tracks){c.save();c.translate(t.x,t.y);c.rotate(t.a);c.globalAlpha=Math.min(.22,t.life/10*.22);c.fillStyle='#151d18';c.fillRect(-23,-13,28,5);c.fillRect(-23,8,28,5);c.restore();}c.globalAlpha=1;}
  drawObstacle(c,o){c.save();c.translate(o.x,o.y);if(o.type==='rock'){c.fillStyle='#555c50';c.beginPath();for(let i=0;i<7;i++){const a=i*Math.PI*2/7,r=o.r*(i%2?.84:1);c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.strokeStyle='#777b68';c.lineWidth=4;c.stroke();}else{c.fillStyle='#8c6240';c.fillRect(-o.r,-o.r,o.r*2,o.r*2);c.strokeStyle='#c59660';c.lineWidth=3;c.strokeRect(-o.r,-o.r,o.r*2,o.r*2);c.beginPath();c.moveTo(-o.r,-o.r);c.lineTo(o.r,o.r);c.moveTo(o.r,-o.r);c.lineTo(-o.r,o.r);c.stroke();}c.restore();}
  drawTank(c,t,player){c.save();c.translate(t.x,t.y);c.rotate(t.angle);const r=t.radius;c.fillStyle='rgba(0,0,0,.28)';c.beginPath();c.ellipse(2,5,r*1.3,r*.9,0,0,Math.PI*2);c.fill();c.fillStyle=player?'#242d28':'#292a25';c.fillRect(-r*1.25,-r*.92,r*2.5,r*.32);c.fillRect(-r*1.25,r*.60,r*2.5,r*.32);c.fillStyle=player?'#66805c':t.boss?'#80654e':'#9c7952';c.fillRect(-r,-r*.72,r*2,r*1.44);c.fillStyle=player?'#8ea477':t.boss?'#ae825e':'#c39b69';c.fillRect(-r*.68,-r*.54,r*1.36,r*1.08);c.fillStyle='#273028';c.fillRect(r*.12,-r*.16,r*1.45,r*.32);c.restore();c.save();c.translate(t.x,t.y);c.rotate(t.turret);c.fillStyle=player?'#c1c9a0':'#d1a16d';c.beginPath();c.arc(0,0,r*.43,0,Math.PI*2);c.fill();c.fillStyle=player?'#778b68':'#a17d59';c.fillRect(-r*.34,-r*.31,r*.68,r*.62);c.fillStyle='#3a3a30';c.fillRect(0,-r*.1,r*1.45,r*.2);c.restore();if(t.flash>0){c.fillStyle='rgba(255,255,210,.45)';c.beginPath();c.arc(t.x,t.y,r+5,0,Math.PI*2);c.fill();}if(!player){const bw=t.boss?74:46;c.fillStyle='#1c211c';c.fillRect(t.x-bw/2,t.y-r-13,bw,5);c.fillStyle=t.boss?'#e9aa4e':'#d05d47';c.fillRect(t.x-bw/2,t.y-r-13,bw*clamp(t.hp/t.maxHp,0,1),5);}}
  drawShot(c,b){c.fillStyle=b.ult?'#fff2a6':b.team==='player'?'#ffd57b':'#ff8d56';c.shadowColor=c.fillStyle;c.shadowBlur=b.ult?18:8;c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.fill();c.shadowBlur=0;}
}
